name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-provisioners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up docker-model-plugin (for llm-model)
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          # Add the repository to Apt sources:
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          
          # Update and Install
          sudo apt-get update
          sudo apt-get install -y docker-model-plugin
      - name: setup-kind-cluster
        run: |
          .scripts/setup-kind-cluster.sh
      - uses: score-spec/setup-score@v2
        with:
          file: score-compose
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: score-spec/setup-score@v2
        with:
          file: score-k8s
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: test-provisioners
        run: |
          .scripts/test-provisioners.sh