name: Compile Hugo

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run hugo
      - run: yarn run dprint check
      - uses: score-spec/setup-score@78de9126e3f298fe8b799b6afb7b0b67bfe0d1e3 # v3.2.0
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
      - run: |
          score-compose init --no-sample
          score-compose generate score.yaml --build main=.
      - run: |
          docker compose up --build -d
      - run: |
          curl $(score-compose resources get-outputs dns.default#score-docs.dns --format '{{ .host }}:8080/docs/')
