name: Compile Hugo

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run hugo
      - run: yarn run dprint check
      - uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
      - run: |
          score-compose init --no-sample
          score-compose generate score.yaml --build main=.
      - run: |
          docker compose up --build -d
      - run: |
          curl $(score-compose resources get-outputs dns.default#score-docs.dns --format '{{ .host }}:8080/docs/')